server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /kafka
spring:
#  webflux:
#    base-path:  /kafka
  main:
    banner-mode: console
  zipkin:
    enabled: false
  sleuth:
    propagation:
      type: B3
  kafka:
    order:
      bootstrap-servers: ${KAFKA_CONNECTION_BOOTSTRAP_SERVERS:localhost:9092}
      topic:
        create-order: create_order
      consumer:
        group-id:
          notification: notification
          service: service
managment:
  endpoints:
    web:
      exposure:
        include: health, prometheus
