server:
  port: ${SERVER_PORT:8080}
spring:
  main:
    banner-mode: off
  zipkin:
    enabled: false
  sleuth:
    propagation:
      type: B3
  kafka:
    order:
      bootstrap-servers: ${KAFKA_CONNECTION_BOOTSTRAP_SERVERS:localhost:9092}
      topic:
        create-order: create-order
      consumer:
        group-id:
          notification: notification
          service: service
managment:
  endpoints:
    web:
      exposure:
        include: health, prometheus
